package com.srparasites.client.model;

import com.srparasites.entity.EntityUnvo;
import net.minecraft.resources.ResourceLocation;
import software.bernie.geckolib.animation.AnimatableManager;
import software.bernie.geckolib.animation.AnimationController;
import software.bernie.geckolib.animation.PlayState;
import software.bernie.geckolib.animation.RawAnimation;
import software.bernie.geckolib.model.GeoModel;

/**
 * GeckoLib 4.x Model class for EntityUnvo.
 * Auto-generated by AnimationController Generator.
 *
 * Category: deterrent
 * Complexity: standard
 * Animations: death, evolved, idle
 *
 * State Machine Priority (highest to lowest):
 *   death: animation.unvo.death
 *   evolved: animation.unvo.evolved
 *   idle: animation.unvo.idle
 *
 * NOTE: In GeckoLib 4.x for MC 1.20.1, registerControllers()
 * is typically on the entity class that implements GeoAnimatable.
 * This generated code can be placed on the model class if your
 * setup delegates to it, or moved to the entity class where
 * event.getAnimatable() will directly return the entity instance.
 */
public class UnvoModel extends GeoModel<EntityUnvo> {

    private static final ResourceLocation MODEL =
        new ResourceLocation("srparasites", "geo/unvo.geo.json");
    private static final ResourceLocation TEXTURE =
        new ResourceLocation("srparasites", "textures/entity/monster/unvo.png");
    private static final ResourceLocation ANIMATION =
        new ResourceLocation("srparasites", "animations/unvo.animation.json");

    @Override
    public ResourceLocation getModelResource(EntityUnvo entity) {
        return MODEL;
    }

    @Override
    public ResourceLocation getTextureResource(EntityUnvo entity) {
        return TEXTURE;
    }

    @Override
    public ResourceLocation getAnimationResource(EntityUnvo entity) {
        return ANIMATION;
    }

    /**
     * Registers animation controllers with state machine logic.
     *
     * In MC 1.12.2, setRotationAngles() was called every frame with
     * embedded if/switch conditions. In GeckoLib 1.20.1, animations are
     * triggered by AnimationController based on entity state queries.
     *
     * The state machine checks conditions in priority order (highest first)
     * and plays the first matching animation. This ensures that death always
     * overrides attack, attack overrides walk, and walk overrides idle.
     *
     * Transition times are tuned to match MC 1.12.2 feel:
     *   - Attack: 3 tick snap transition (responsive combat)
     *   - Walk/Idle: 4-5 tick smooth blend (natural movement)
     *   - Evolved: 15 tick slow morph (dramatic transformation)
     *   - Sleeping: 10 tick gentle transition (peaceful rest)
     */
    @Override
    public void registerControllers(AnimatableManager.ControllerRegistrar controllers) {
        // ========================================================================
        // Main Animation Controller - State Machine
        // ========================================================================
        // Priority order: death > evolved > idle
        // Each state is checked in order; the first matching condition wins.
        // Idle is always the fallback (condition: true) so the controller
        // never returns PlayState.STOP for normal entity states.
        controllers.add(new AnimationController<>(this, "mainController", 5f, event -> {
            EntityUnvo entity = event.getAnimatable();

            // Death - plays once when entity dies, overrides everything
            if (entity.isDeadOrDying()) {
                event.getController().setAnimation(
                    RawAnimation.begin().thenPlay("animation.unvo.death")
                );
                return PlayState.CONTINUE;
            }

            // Evolved - loops when entity has evolved/transformed
            if (entity.isEvolved()) {
                event.getController().setAnimation(
                    RawAnimation.begin().thenLoop("animation.unvo.evolved")
                );
                return PlayState.CONTINUE;
            }

            // Idle - default fallback, always loops
            if (true) {
                event.getController().setAnimation(
                    RawAnimation.begin().thenLoop("animation.unvo.idle")
                );
                return PlayState.CONTINUE;
            }

            // No matching state - stop animation
            return PlayState.STOP;
        }));
    }
}
