package com.srparasites.client.model;

import com.srparasites.entity.EntityHeblu;
import net.minecraft.resources.ResourceLocation;
import software.bernie.geckolib.animation.AnimatableManager;
import software.bernie.geckolib.animation.AnimationController;
import software.bernie.geckolib.animation.PlayState;
import software.bernie.geckolib.animation.RawAnimation;
import software.bernie.geckolib.model.GeoModel;

/**
 * GeckoLib 4.x Model class for EntityHeblu.
 * Auto-generated by AnimationController Generator.
 *
 * Category: derived
 * Complexity: complex
 * Animations: attack, fly, idle, special
 *
 * State Machine Priority (highest to lowest):
 *   special: animation.heblu.cosmic, animation.heblu.shaking, animation.heblu.vomit
 *   attack: animation.heblu.attack
 *   fly: animation.heblu.fly
 *   idle: animation.heblu.idle
 *
 * NOTE: In GeckoLib 4.x for MC 1.20.1, registerControllers()
 * is typically on the entity class that implements GeoAnimatable.
 * This generated code can be placed on the model class if your
 * setup delegates to it, or moved to the entity class where
 * event.getAnimatable() will directly return the entity instance.
 */
public class HebluModel extends GeoModel<EntityHeblu> {

    private static final ResourceLocation MODEL =
        new ResourceLocation("srparasites", "geo/heblu.geo.json");
    private static final ResourceLocation TEXTURE =
        new ResourceLocation("srparasites", "textures/entity/monster/heblu.png");
    private static final ResourceLocation ANIMATION =
        new ResourceLocation("srparasites", "animations/heblu.animation.json");

    @Override
    public ResourceLocation getModelResource(EntityHeblu entity) {
        return MODEL;
    }

    @Override
    public ResourceLocation getTextureResource(EntityHeblu entity) {
        return TEXTURE;
    }

    @Override
    public ResourceLocation getAnimationResource(EntityHeblu entity) {
        return ANIMATION;
    }

    /**
     * Registers animation controllers with state machine logic.
     *
     * In MC 1.12.2, setRotationAngles() was called every frame with
     * embedded if/switch conditions. In GeckoLib 1.20.1, animations are
     * triggered by AnimationController based on entity state queries.
     *
     * The state machine checks conditions in priority order (highest first)
     * and plays the first matching animation. This ensures that death always
     * overrides attack, attack overrides walk, and walk overrides idle.
     *
     * Transition times are tuned to match MC 1.12.2 feel:
     *   - Attack: 3 tick snap transition (responsive combat)
     *   - Walk/Idle: 4-5 tick smooth blend (natural movement)
     *   - Evolved: 15 tick slow morph (dramatic transformation)
     *   - Sleeping: 10 tick gentle transition (peaceful rest)
     */
    @Override
    public void registerControllers(AnimatableManager.ControllerRegistrar controllers) {
        // ========================================================================
        // Main Animation Controller - State Machine
        // ========================================================================
        // Priority order: special > attack > fly > idle
        // Each state is checked in order; the first matching condition wins.
        // Idle is always the fallback (condition: true) so the controller
        // never returns PlayState.STOP for normal entity states.
        controllers.add(new AnimationController<>(this, "mainController", 5f, event -> {
            EntityHeblu entity = event.getAnimatable();

            // Special - entity-specific state (vomit/shaking/cosmic)
            if (entity.isCosmic()) {
                event.getController().setAnimation(
                    RawAnimation.begin().thenLoop("animation.heblu.cosmic")
                );
                return PlayState.CONTINUE;
            }

            // Special - entity-specific state (vomit/shaking/cosmic)
            if (entity.isShaking()) {
                event.getController().setAnimation(
                    RawAnimation.begin().thenLoop("animation.heblu.shaking")
                );
                return PlayState.CONTINUE;
            }

            // Special - entity-specific state (vomit/shaking/cosmic)
            if (entity.isVomiting()) {
                event.getController().setAnimation(
                    RawAnimation.begin().thenLoop("animation.heblu.vomit")
                );
                return PlayState.CONTINUE;
            }

            // Attack - plays once when entity has a target
            if (entity.getTarget() != null) {
                event.getController().setAnimation(
                    RawAnimation.begin().thenPlay("animation.heblu.attack")
                );
                return PlayState.CONTINUE;
            }

            // Flying - loops when entity is airborne
            if (!entity.onGround()) {
                event.getController().setAnimation(
                    RawAnimation.begin().thenLoop("animation.heblu.fly")
                );
                return PlayState.CONTINUE;
            }

            // Idle - default fallback, always loops
            if (true) {
                event.getController().setAnimation(
                    RawAnimation.begin().thenLoop("animation.heblu.idle")
                );
                return PlayState.CONTINUE;
            }

            // No matching state - stop animation
            return PlayState.STOP;
        }));
    }
}
