"""
Runtime Variable Sampler (v6.9.19)

Provides runtime variable values for MVE evaluation. Two modes:

1. **Sampling Library mode**: Loads pre-recorded runtime variable
   sequences from a Mixin-captured JSONL file. Each tick's
   getBODY()/getAttackTimer()/limbSwing/etc. values are looked up
   by tick number.

2. **Molang mode**: Returns Molang expressions for GeckoLib runtime
   evaluation (e.g., getBODY() -> "v.body").

The sampling library is generated by a Mixin mod that hooks into
SRP's setRotationAngles at runtime, recording all parameter values
per tick. See `mixin/` directory for the Mixin mod source.
"""

import json
import os
import math
import logging
from typing import Dict, Optional, Any
from pathlib import Path

logger = logging.getLogger(__name__)


class RuntimeSampler:
    """Manages runtime variable values for MVE evaluation."""

    def __init__(self, sampling_lib_path: Optional[str] = None):
        """Initialize the runtime sampler.

        Args:
            sampling_lib_path: Path to the sampling library JSONL file.
                If None, uses Molang expressions (no real values).
        """
        self.sampling_lib = {}
        self.use_molang = (sampling_lib_path is None)

        if sampling_lib_path and os.path.exists(sampling_lib_path):
            self._load_sampling_lib(sampling_lib_path)
            self.use_molang = False
            logger.info("Loaded runtime sampling library: %s (%d ticks)",
                        sampling_lib_path, len(self.sampling_lib))

    def _load_sampling_lib(self, path: str):
        """Load a JSONL sampling library file.

        Each line is a JSON object:
        {"tick": 0, "getBODY": 0.0, "getAttackTimer": 0.0, ...}
        """
        with open(path, 'r', encoding='utf-8') as f:
            for line in f:
                try:
                    entry = json.loads(line.strip())
                    tick = entry.get('tick', 0)
                    self.sampling_lib[tick] = entry
                except (json.JSONDecodeError, KeyError):
                    continue

    def get_runtime_value(self, method_name: str, tick: float,
                          default: float = 0.0) -> Any:
        """Get a runtime variable value at a given tick.

        Args:
            method_name: Runtime method name (e.g., 'getBODY')
            tick: Tick number (float for interpolation)
            default: Default value if not in sampling library

        Returns:
            Float value (sampling mode) or Molang string (Molang mode)
        """
        if self.use_molang:
            # Return Molang expression
            molang_map = {
                'getBODY': 'v.body',
                'getFloorTimer': 'v.floor_timer',
                'getAttackTimer': 'v.attack_timer',
                'shakingC': 'v.shaking_count',
                'getStillAni': 'v.still_ani',
                'getCloneC': 'v.clone_c',
                'showC': 'v.show_c',
                'getLeft': 'v.left',
                'getRight': 'v.right',
                'getHead': 'v.head',
            }
            return molang_map.get(method_name, str(default))

        # Sampling library mode: interpolate between ticks
        tick_int = int(tick)
        tick_frac = tick - tick_int

        entry_low = self.sampling_lib.get(tick_int, {})
        entry_high = self.sampling_lib.get(tick_int + 1, entry_low)

        val_low = entry_low.get(method_name, default)
        val_high = entry_high.get(method_name, val_low)

        # Linear interpolation
        if isinstance(val_low, (int, float)) and isinstance(val_high, (int, float)):
            return val_low * (1 - tick_frac) + val_high * tick_frac
        return val_low

    def get_limb_swing(self, tick: float) -> Any:
        """Get limbSwing value at a given tick."""
        if self.use_molang:
            return 'query.modified_move_speed * 20'
        return self.get_runtime_value('limbSwing', tick, tick * 20.0)

    def get_limb_swing_amount(self, tick: float) -> Any:
        """Get limbSwingAmount value at a given tick."""
        if self.use_molang:
            return 'math.clamp(query.modified_move_speed * 20, 0, 1)'
        return self.get_runtime_value('limbSwingAmount', tick, 0.5)

    def is_molang_mode(self) -> bool:
        """Check if operating in Molang expression mode."""
        return self.use_molang
