// === idle state ===
// Auto-generated by MC1122 -> GeckoLib Animation Converter
// Class A-2: Movement-driven animation (limbSwing dependent)
// Place this code in your GeoModel's codeAnimations method

// Get animation parameters from entity
float limbSwing = animatable.limbSwing;
float limbSwingAmount = animatable.limbSwingAmount;
float ageInTicks = animatable.ageInTicks;

// Intermediate variables (resolved from original code)
float f1 = (float)(Math.cos((ageInTicks * 0.1f)) * 0.3f);
float f1_v2 = (float)(Math.cos((ageInTicks * 0.09f)) * 0.08f);
float f1_v3 = (float)(Math.cos((ageInTicks * 0.015f)) * 0.02f);
float f2 = (float)(Math.cos((ageInTicks * 0.17f)) * 0.21f);
float f3 = (float)(Math.cos((ageInTicks * 0.16f)) * 0.22f);
float f1_v4 = (float)(Math.cos((ageInTicks * 0.0751f)) * 0.06f);
float f2_v2 = (float)(Math.cos((ageInTicks * 0.0872f)) * 0.0411f);
float f3_v2 = (float)(Math.cos((ageInTicks * 0.09669f)) * 0.075f);
float f1_v5 = (float)(Math.cos((ageInTicks * 0.091f)) * 0.1f);
float f1_v6 = (float)(Math.cos((ageInTicks * 0.123f)) * 0.25f);
float f2_v3 = (float)(Math.cos((ageInTicks * 0.233f)) * 0.21f);
float f3_v3 = (float)(Math.cos((ageInTicks * 0.1435f)) * 0.29f);
float f4 = (float)(Math.cos((ageInTicks * 0.2f)) * 0.24f);
float f1_v7 = (float)(Math.cos((ageInTicks * 0.123f)) * 0.25f);
float f2_v4 = (float)(Math.cos((ageInTicks * 0.233f)) * 0.21f);
float f3_v4 = (float)(Math.cos((ageInTicks * 0.1435f)) * 0.29f);
float f4_v2 = (float)(Math.cos((ageInTicks * 0.2f)) * 0.24f);

// Bone animation assignments:
GeoBone jointBBLLBone = this.getAnimationProcessor().getBone("jointBBLL");
if (jointBBLLBone != null) {
    jointBBLLBone.setRotationX((float)(((1 * limbSwingAmount * 1.1f * GD) * Math.cos((limbSwing * 0.3f * GS + -1.0f)) + (0.0f * limbSwingAmount))));
}

GeoBone jointBBRLBone = this.getAnimationProcessor().getBone("jointBBRL");
if (jointBBRLBone != null) {
    jointBBRLBone.setRotationX((float)(((-1 * limbSwingAmount * 1.1f * GD) * Math.cos((limbSwing * 0.3f * GS + -1.0f)) + (0.0f * limbSwingAmount))));
}

GeoBone jointBBLL_2Bone = this.getAnimationProcessor().getBone("jointBBLL_2");
if (jointBBLL_2Bone != null) {
    jointBBLL_2Bone.setRotationX((float)(((1 * limbSwingAmount * 1.1f * GD) * Math.cos((limbSwing * 0.3f * GS + 1.0f)) + (0.0f * limbSwingAmount))));
}

GeoBone jointBBRL_2Bone = this.getAnimationProcessor().getBone("jointBBRL_2");
if (jointBBRL_2Bone != null) {
    jointBBRL_2Bone.setRotationX((float)(((-1 * limbSwingAmount * 1.1f * GD) * Math.cos((limbSwing * 0.3f * GS + 1.0f)) + (0.0f * limbSwingAmount))));
}

GeoBone jointBLLBone = this.getAnimationProcessor().getBone("jointBLL");
if (jointBLLBone != null) {
    jointBLLBone.setRotationX((float)(((-1 * limbSwingAmount * 1.5f * GD) * Math.cos((limbSwing * 0.3f * GS + 1.0f)) + (-0.0f * limbSwingAmount))));
}

GeoBone jointBRLBone = this.getAnimationProcessor().getBone("jointBRL");
if (jointBRLBone != null) {
    jointBRLBone.setRotationX((float)(((1 * limbSwingAmount * 1.5f * GD) * Math.cos((limbSwing * 0.3f * GS + 1.0f)) + (-0.0f * limbSwingAmount))));
}

GeoBone jointBLL_2Bone = this.getAnimationProcessor().getBone("jointBLL_2");
if (jointBLL_2Bone != null) {
    jointBLL_2Bone.setRotationX((float)(((1 * limbSwingAmount * 1.5f * GD) * Math.cos((limbSwing * 0.3f * GS + -1.0f)) + (0.0f * limbSwingAmount))));
}

GeoBone jointBRL_2Bone = this.getAnimationProcessor().getBone("jointBRL_2");
if (jointBRL_2Bone != null) {
    jointBRL_2Bone.setRotationX((float)(((-1 * limbSwingAmount * 1.5f * GD) * Math.cos((limbSwing * 0.3f * GS + -1.0f)) + (0.0f * limbSwingAmount))));
}

GeoBone jointFLLBone = this.getAnimationProcessor().getBone("jointFLL");
if (jointFLLBone != null) {
    jointFLLBone.setRotationX((float)(((1 * limbSwingAmount * 1.5f * GD) * Math.cos((limbSwing * 0.3f * GS + 1.0f)) + (-0.4f * limbSwingAmount))));
}

GeoBone jointFLBone = this.getAnimationProcessor().getBone("jointFL");
if (jointFLBone != null) {
    jointFLBone.setRotationX((float)(((-1 * limbSwingAmount * 1.5f * GD) * Math.cos((limbSwing * 0.3f * GS + 1.0f)) + (-0.4f * limbSwingAmount))));
}

GeoBone jointFLL_1Bone = this.getAnimationProcessor().getBone("jointFLL_1");
if (jointFLL_1Bone != null) {
    jointFLL_1Bone.setRotationX((float)(((1 * limbSwingAmount * 1.5f * GD) * Math.cos((limbSwing * 0.3f * GS + -1.0f)) + (0.0f * limbSwingAmount))));
}

GeoBone jointFRLBone = this.getAnimationProcessor().getBone("jointFRL");
if (jointFRLBone != null) {
    jointFRLBone.setRotationX((float)(((-1 * limbSwingAmount * 1.5f * GD) * Math.cos((limbSwing * 0.3f * GS + -1.0f)) + (0.0f * limbSwingAmount))));
}

GeoBone jointFFLLBone = this.getAnimationProcessor().getBone("jointFFLL");
if (jointFFLLBone != null) {
    jointFFLLBone.setRotationX((float)(((-1 * limbSwingAmount * 1.1f * GD) * Math.cos((limbSwing * 0.3f * GS + 1.0f)) + (-0.1f * limbSwingAmount))));
}

GeoBone jointFFRLBone = this.getAnimationProcessor().getBone("jointFFRL");
if (jointFFRLBone != null) {
    jointFFRLBone.setRotationX((float)(((1 * limbSwingAmount * 1.1f * GD) * Math.cos((limbSwing * 0.3f * GS + 1.0f)) + (-0.1f * limbSwingAmount))));
}

GeoBone jointFFLL_1Bone = this.getAnimationProcessor().getBone("jointFFLL_1");
if (jointFFLL_1Bone != null) {
    jointFFLL_1Bone.setRotationX((float)(((-1 * limbSwingAmount * 1.1f * GD) * Math.cos((limbSwing * 0.3f * GS + -1.0f)) + (0.0f * limbSwingAmount))));
}

GeoBone jointFFRL_1Bone = this.getAnimationProcessor().getBone("jointFFRL_1");
if (jointFFRL_1Bone != null) {
    jointFFRL_1Bone.setRotationX((float)(((1 * limbSwingAmount * 1.1f * GD) * Math.cos((limbSwing * 0.3f * GS + -1.0f)) + (0.0f * limbSwingAmount))));
}

GeoBone mainbodyBone = this.getAnimationProcessor().getBone("mainbody");
if (mainbodyBone != null) {
    mainbodyBone.setPosZ((float)(-(1 * Math.cos((limbSwing * 0.6f * GS)) * limbSwingAmount * 0.18f)));
}


// === flying state ===
// Auto-generated by MC1122 -> GeckoLib Animation Converter
// Class A-2: Movement-driven animation (limbSwing dependent)
// Place this code in your GeoModel's codeAnimations method

// Get animation parameters from entity
float limbSwing = animatable.limbSwing;
float limbSwingAmount = animatable.limbSwingAmount;
float ageInTicks = animatable.ageInTicks;

// Intermediate variables (resolved from original code)
float f12 = (float)(Math.cos((ageInTicks * 0.09f)) * 0.18f);
float f12_v2 = (float)(Math.cos((ageInTicks * speed)) * 0.72f);
float f12_v3 = (float)(Math.cos((ageInTicks * speed)) * 0.12f);
float f12_v4 = (float)(Math.cos((ageInTicks * speed)) * 0.1f);
float f12_v5 = (float)(Math.cos((ageInTicks * speed)) * 0.111f);
float f12_v6 = (float)(Math.cos((ageInTicks * 0.0751f)) * 0.0512106f);
float f22 = (float)(Math.cos((ageInTicks * 0.0872f)) * 0.06107411f);
float f32 = (float)(Math.cos((ageInTicks * 0.09669f)) * 0.0515075f);
float f4 = (float)(Math.cos((ageInTicks * 0.079f)) * 0.04575f);
float f12_v7 = (float)(Math.cos((ageInTicks * 0.14f)) * 0.4f);
float f12_v8 = (float)(Math.cos((ageInTicks * 0.123f)) * 0.25f);
float f22_v2 = (float)(Math.cos((ageInTicks * 0.233f)) * 0.21f);
float f32_v2 = (float)(Math.cos((ageInTicks * 0.1435f)) * 0.29f);
float f4_v2 = (float)(Math.cos((ageInTicks * 0.2f)) * 0.24f);
float f12_v9 = (float)(Math.cos((ageInTicks * 0.123f)) * 0.25f);
float f22_v3 = (float)(Math.cos((ageInTicks * 0.233f)) * 0.21f);
float f32_v3 = (float)(Math.cos((ageInTicks * 0.1435f)) * 0.29f);
float f4_v3 = (float)(Math.cos((ageInTicks * 0.2f)) * 0.24f);
float f12_v10 = (float)(Math.cos((ageInTicks * 0.0751f)) * 0.02106f);
float f22_v4 = (float)(Math.cos((ageInTicks * 0.0872f)) * 0.0107411f);
float f32_v4 = (float)(Math.cos((ageInTicks * 0.09669f)) * 0.015075f);
float f12_v11 = (float)(Math.cos((ageInTicks * 0.061f)) * 0.035f);
float f22_v5 = (float)(Math.cos((ageInTicks * 0.082f)) * 0.02511f);
float f32_v5 = (float)(Math.cos((ageInTicks * 0.079f)) * 0.04575f);

// Bone animation assignments:
GeoBone jointLW1_1Bone = this.getAnimationProcessor().getBone("jointLW1_1");
if (jointLW1_1Bone != null) {
    jointLW1_1Bone.setRotationZ((float)(-(((1 * limbSwingAmount * 2.0f) * Math.cos((limbSwing * speed + -2.0f)) + (0.8f * limbSwingAmount)))));
}

GeoBone jointLW2Bone = this.getAnimationProcessor().getBone("jointLW2");
if (jointLW2Bone != null) {
    jointLW2Bone.setRotationZ((float)(-(((1 * limbSwingAmount * 1.9f) * Math.cos((limbSwing * speed + 2.5f)) + (-1.0f * limbSwingAmount)))));
}

GeoBone jointRW1_1Bone = this.getAnimationProcessor().getBone("jointRW1_1");
if (jointRW1_1Bone != null) {
    jointRW1_1Bone.setRotationZ((float)(-(((-1 * limbSwingAmount * 2.0f) * Math.cos((limbSwing * speed + -2.0f)) + (-0.8f * limbSwingAmount)))));
}

GeoBone jointRW2Bone = this.getAnimationProcessor().getBone("jointRW2");
if (jointRW2Bone != null) {
    jointRW2Bone.setRotationZ((float)(-(((-1 * limbSwingAmount * 1.9f) * Math.cos((limbSwing * speed + 2.5f)) + (1.0f * limbSwingAmount)))));
}


// === evolved state ===
// Auto-generated by MC1122 -> GeckoLib Animation Converter
// Class A-2: Movement-driven animation (limbSwing dependent)
// Place this code in your GeoModel's codeAnimations method

// Get animation parameters from entity
float limbSwing = animatable.limbSwing;
float limbSwingAmount = animatable.limbSwingAmount;
float ageInTicks = animatable.ageInTicks;

// Intermediate variables (resolved from original code)
float f1 = (float)(Math.cos((ageInTicks * 0.1f)) * 0.3f);
float f1_v2 = (float)(Math.cos((ageInTicks * 0.09f)) * 0.08f);
float f1_v3 = (float)(Math.cos((ageInTicks * 0.015f)) * 0.052f);
float f2 = (float)(Math.cos((ageInTicks * 0.17f)) * 0.421f);
float f3 = (float)(Math.cos((ageInTicks * 0.16f)) * 0.5422f);
float f1_v4 = (float)(Math.cos((ageInTicks * 0.0751f)) * 0.2106f);
float f2_v2 = (float)(Math.cos((ageInTicks * 0.0872f)) * 0.107411f);
float f3_v2 = (float)(Math.cos((ageInTicks * 0.09669f)) * 0.15075f);
float f1_v5 = (float)(Math.cos((ageInTicks * 0.191f)) * 0.2f);
float f1_v6 = (float)(Math.cos((ageInTicks * 0.123f)) * 0.25f);
float f2_v3 = (float)(Math.cos((ageInTicks * 0.233f)) * 0.21f);
float f3_v3 = (float)(Math.cos((ageInTicks * 0.1435f)) * 0.29f);
float f4 = (float)(Math.cos((ageInTicks * 0.2f)) * 0.24f);
float f1_v7 = (float)(Math.cos((ageInTicks * 0.123f)) * 0.25f);
float f2_v4 = (float)(Math.cos((ageInTicks * 0.233f)) * 0.21f);
float f3_v4 = (float)(Math.cos((ageInTicks * 0.1435f)) * 0.29f);
float f4_v2 = (float)(Math.cos((ageInTicks * 0.2f)) * 0.24f);

// Bone animation assignments:
GeoBone jointBBLLBone = this.getAnimationProcessor().getBone("jointBBLL");
if (jointBBLLBone != null) {
    jointBBLLBone.setRotationX((float)(((1 * limbSwingAmount * 1.1f * GD) * Math.cos((limbSwing * 0.3f * GS + -1.0f)) + (0.0f * limbSwingAmount))));
}

GeoBone jointBBRLBone = this.getAnimationProcessor().getBone("jointBBRL");
if (jointBBRLBone != null) {
    jointBBRLBone.setRotationX((float)(((-1 * limbSwingAmount * 1.1f * GD) * Math.cos((limbSwing * 0.3f * GS + -1.0f)) + (0.0f * limbSwingAmount))));
}

GeoBone jointBBLL_2Bone = this.getAnimationProcessor().getBone("jointBBLL_2");
if (jointBBLL_2Bone != null) {
    jointBBLL_2Bone.setRotationX((float)(((1 * limbSwingAmount * 1.1f * GD) * Math.cos((limbSwing * 0.3f * GS + 1.0f)) + (0.0f * limbSwingAmount))));
}

GeoBone jointBBRL_2Bone = this.getAnimationProcessor().getBone("jointBBRL_2");
if (jointBBRL_2Bone != null) {
    jointBBRL_2Bone.setRotationX((float)(((-1 * limbSwingAmount * 1.1f * GD) * Math.cos((limbSwing * 0.3f * GS + 1.0f)) + (0.0f * limbSwingAmount))));
}

GeoBone jointBLLBone = this.getAnimationProcessor().getBone("jointBLL");
if (jointBLLBone != null) {
    jointBLLBone.setRotationX((float)(((-1 * limbSwingAmount * 1.5f * GD) * Math.cos((limbSwing * 0.3f * GS + 1.0f)) + (-0.0f * limbSwingAmount))));
}

GeoBone jointBRLBone = this.getAnimationProcessor().getBone("jointBRL");
if (jointBRLBone != null) {
    jointBRLBone.setRotationX((float)(((1 * limbSwingAmount * 1.5f * GD) * Math.cos((limbSwing * 0.3f * GS + 1.0f)) + (-0.0f * limbSwingAmount))));
}

GeoBone jointBLL_2Bone = this.getAnimationProcessor().getBone("jointBLL_2");
if (jointBLL_2Bone != null) {
    jointBLL_2Bone.setRotationX((float)(((1 * limbSwingAmount * 1.5f * GD) * Math.cos((limbSwing * 0.3f * GS + -1.0f)) + (0.0f * limbSwingAmount))));
}

GeoBone jointBRL_2Bone = this.getAnimationProcessor().getBone("jointBRL_2");
if (jointBRL_2Bone != null) {
    jointBRL_2Bone.setRotationX((float)(((-1 * limbSwingAmount * 1.5f * GD) * Math.cos((limbSwing * 0.3f * GS + -1.0f)) + (0.0f * limbSwingAmount))));
}

GeoBone jointFLLBone = this.getAnimationProcessor().getBone("jointFLL");
if (jointFLLBone != null) {
    jointFLLBone.setRotationX((float)(((1 * limbSwingAmount * 1.5f * GD) * Math.cos((limbSwing * 0.3f * GS + 1.0f)) + (-0.4f * limbSwingAmount))));
}

GeoBone jointFLBone = this.getAnimationProcessor().getBone("jointFL");
if (jointFLBone != null) {
    jointFLBone.setRotationX((float)(((-1 * limbSwingAmount * 1.5f * GD) * Math.cos((limbSwing * 0.3f * GS + 1.0f)) + (-0.4f * limbSwingAmount))));
}

GeoBone jointFLL_1Bone = this.getAnimationProcessor().getBone("jointFLL_1");
if (jointFLL_1Bone != null) {
    jointFLL_1Bone.setRotationX((float)(((1 * limbSwingAmount * 1.5f * GD) * Math.cos((limbSwing * 0.3f * GS + -1.0f)) + (0.0f * limbSwingAmount))));
}

GeoBone jointFRLBone = this.getAnimationProcessor().getBone("jointFRL");
if (jointFRLBone != null) {
    jointFRLBone.setRotationX((float)(((-1 * limbSwingAmount * 1.5f * GD) * Math.cos((limbSwing * 0.3f * GS + -1.0f)) + (0.0f * limbSwingAmount))));
}

GeoBone jointFFLLBone = this.getAnimationProcessor().getBone("jointFFLL");
if (jointFFLLBone != null) {
    jointFFLLBone.setRotationX((float)(((-1 * limbSwingAmount * 1.1f * GD) * Math.cos((limbSwing * 0.3f * GS + 1.0f)) + (-0.1f * limbSwingAmount))));
}

GeoBone jointFFRLBone = this.getAnimationProcessor().getBone("jointFFRL");
if (jointFFRLBone != null) {
    jointFFRLBone.setRotationX((float)(((1 * limbSwingAmount * 1.1f * GD) * Math.cos((limbSwing * 0.3f * GS + 1.0f)) + (-0.1f * limbSwingAmount))));
}

GeoBone jointFFLL_1Bone = this.getAnimationProcessor().getBone("jointFFLL_1");
if (jointFFLL_1Bone != null) {
    jointFFLL_1Bone.setRotationX((float)(((-1 * limbSwingAmount * 1.1f * GD) * Math.cos((limbSwing * 0.3f * GS + -1.0f)) + (0.0f * limbSwingAmount))));
}

GeoBone jointFFRL_1Bone = this.getAnimationProcessor().getBone("jointFFRL_1");
if (jointFFRL_1Bone != null) {
    jointFFRL_1Bone.setRotationX((float)(((1 * limbSwingAmount * 1.1f * GD) * Math.cos((limbSwing * 0.3f * GS + -1.0f)) + (0.0f * limbSwingAmount))));
}

GeoBone mainbodyBone = this.getAnimationProcessor().getBone("mainbody");
if (mainbodyBone != null) {
    mainbodyBone.setPosZ((float)(-(1 * Math.cos((limbSwing * 0.6f * GS)) * limbSwingAmount * 0.2f)));
}
