package com.srparasites.client.model;

import com.srparasites.entity.EntityHost;
import net.minecraft.resources.ResourceLocation;
import software.bernie.geckolib.animation.AnimatableManager;
import software.bernie.geckolib.animation.AnimationController;
import software.bernie.geckolib.animation.PlayState;
import software.bernie.geckolib.animation.RawAnimation;
import software.bernie.geckolib.model.GeoModel;

/**
 * GeckoLib 4.x Model class for EntityHost.
 * Auto-generated by AnimationController Generator.
 *
 * Category: crude
 * Complexity: state
 * Animations: closed, open
 *
 * State Machine Priority (highest to lowest):
 *   open: animation.host.open
 *   closed: animation.host.closed
 *
 * NOTE: In GeckoLib 4.x for MC 1.20.1, registerControllers()
 * is typically on the entity class that implements GeoAnimatable.
 * This generated code can be placed on the model class if your
 * setup delegates to it, or moved to the entity class where
 * event.getAnimatable() will directly return the entity instance.
 */
public class HostModel extends GeoModel<EntityHost> {

    private static final ResourceLocation MODEL =
        new ResourceLocation("srparasites", "geo/host.geo.json");
    private static final ResourceLocation TEXTURE =
        new ResourceLocation("srparasites", "textures/entity/monster/host.png");
    private static final ResourceLocation ANIMATION =
        new ResourceLocation("srparasites", "animations/host.animation.json");

    @Override
    public ResourceLocation getModelResource(EntityHost entity) {
        return MODEL;
    }

    @Override
    public ResourceLocation getTextureResource(EntityHost entity) {
        return TEXTURE;
    }

    @Override
    public ResourceLocation getAnimationResource(EntityHost entity) {
        return ANIMATION;
    }

    /**
     * Registers animation controllers with state machine logic.
     *
     * In MC 1.12.2, setRotationAngles() was called every frame with
     * embedded if/switch conditions. In GeckoLib 1.20.1, animations are
     * triggered by AnimationController based on entity state queries.
     *
     * The state machine checks conditions in priority order (highest first)
     * and plays the first matching animation. This ensures that death always
     * overrides attack, attack overrides walk, and walk overrides idle.
     *
     * Transition times are tuned to match MC 1.12.2 feel:
     *   - Attack: 3 tick snap transition (responsive combat)
     *   - Walk/Idle: 4-5 tick smooth blend (natural movement)
     *   - Evolved: 15 tick slow morph (dramatic transformation)
     *   - Sleeping: 10 tick gentle transition (peaceful rest)
     */
    @Override
    public void registerControllers(AnimatableManager.ControllerRegistrar controllers) {
        // ========================================================================
        // State-based Controller (open/closed)
        // ========================================================================
        // Models like host and hostII use open/closed states instead of
        // idle/walk. The entity's isOpen() method determines which plays.
        controllers.add(new AnimationController<>(this, "stateController", 5f, event -> {
            EntityHost entity = event.getAnimatable();

            // Open state - entity is opened/activated
            if (entity.isOpen()) {
                event.getController().setAnimation(
                    RawAnimation.begin().thenLoop("animation.host.open")
                );
                return PlayState.CONTINUE;
            }

            // Closed state - entity is closed/dormant (default)
            event.getController().setAnimation(
                RawAnimation.begin().thenLoop("animation.host.closed")
            );
            return PlayState.CONTINUE;
        }));
    }
}
