package com.srparasites.client.model;

import com.srparasites.entity.EntityNULL;
import net.minecraft.resources.ResourceLocation;
import software.bernie.geckolib.animation.AnimatableManager;
import software.bernie.geckolib.animation.AnimationController;
import software.bernie.geckolib.animation.PlayState;
import software.bernie.geckolib.animation.RawAnimation;
import software.bernie.geckolib.model.GeoModel;

/**
 * GeckoLib 4.x Model class for EntityNULL.
 * Auto-generated by AnimationController Generator.
 *
 * Category: misc
 * Complexity: simple
 * Animations: idle
 *
 * State Machine Priority (highest to lowest):
 *   idle: animation.null.idle
 *
 * NOTE: In GeckoLib 4.x for MC 1.20.1, registerControllers()
 * is typically on the entity class that implements GeoAnimatable.
 * This generated code can be placed on the model class if your
 * setup delegates to it, or moved to the entity class where
 * event.getAnimatable() will directly return the entity instance.
 */
public class NULLModel extends GeoModel<EntityNULL> {

    private static final ResourceLocation MODEL =
        new ResourceLocation("srparasites", "geo/nULL.geo.json");
    private static final ResourceLocation TEXTURE =
        new ResourceLocation("srparasites", "textures/entity/monster/nULL.png");
    private static final ResourceLocation ANIMATION =
        new ResourceLocation("srparasites", "animations/nULL.animation.json");

    @Override
    public ResourceLocation getModelResource(EntityNULL entity) {
        return MODEL;
    }

    @Override
    public ResourceLocation getTextureResource(EntityNULL entity) {
        return TEXTURE;
    }

    @Override
    public ResourceLocation getAnimationResource(EntityNULL entity) {
        return ANIMATION;
    }

    /**
     * Registers animation controllers with state machine logic.
     *
     * In MC 1.12.2, setRotationAngles() was called every frame with
     * embedded if/switch conditions. In GeckoLib 1.20.1, animations are
     * triggered by AnimationController based on entity state queries.
     *
     * The state machine checks conditions in priority order (highest first)
     * and plays the first matching animation. This ensures that death always
     * overrides attack, attack overrides walk, and walk overrides idle.
     *
     * Transition times are tuned to match MC 1.12.2 feel:
     *   - Attack: 3 tick snap transition (responsive combat)
     *   - Walk/Idle: 4-5 tick smooth blend (natural movement)
     *   - Evolved: 15 tick slow morph (dramatic transformation)
     *   - Sleeping: 10 tick gentle transition (peaceful rest)
     */
    @Override
    public void registerControllers(AnimatableManager.ControllerRegistrar controllers) {
        // Simple idle-only controller
        // This model has only an idle animation, so we use a
        // straightforward controller that always loops the idle anim.
        controllers.add(new AnimationController<>(this, "idleController", 5f, event -> {
            event.getController().setAnimation(
                RawAnimation.begin().thenLoop("animation.null.idle")
            );
            return PlayState.CONTINUE;
        }));
    }
}
