package com.srparasites.client.model;

import com.srparasites.entity.EntityInfPig;
import net.minecraft.resources.ResourceLocation;
import software.bernie.geckolib.animation.AnimatableManager;
import software.bernie.geckolib.animation.AnimationController;
import software.bernie.geckolib.animation.PlayState;
import software.bernie.geckolib.animation.RawAnimation;
import software.bernie.geckolib.model.GeoModel;

/**
 * GeckoLib 4.x Model class for EntityInfPig.
 * Auto-generated by AnimationController Generator.
 *
 * Category: infected
 * Complexity: complex
 * Animations: attack, idle, stage, walk
 *
 * State Machine Priority (highest to lowest):
 *   attack: animation.infpig.attack
 *   walk: animation.infpig.walk
 *   stage: animation.infpig.stage6
 *   idle: animation.infpig.idle
 *
 * NOTE: In GeckoLib 4.x for MC 1.20.1, registerControllers()
 * is typically on the entity class that implements GeoAnimatable.
 * This generated code can be placed on the model class if your
 * setup delegates to it, or moved to the entity class where
 * event.getAnimatable() will directly return the entity instance.
 */
public class InfPigModel extends GeoModel<EntityInfPig> {

    private static final ResourceLocation MODEL =
        new ResourceLocation("srparasites", "geo/infPig.geo.json");
    private static final ResourceLocation TEXTURE =
        new ResourceLocation("srparasites", "textures/entity/monster/infPig.png");
    private static final ResourceLocation ANIMATION =
        new ResourceLocation("srparasites", "animations/infPig.animation.json");

    // ========================================================================
    // limbSwingAmount Lerp Simulation
    // ========================================================================
    // Replicates MC 1.12.2's exponential decay smoothing for walk detection.
    // In vanilla MC, the limbSwingAmount is interpolated each frame using:
    //   limbSwingAmount += (targetAmount - limbSwingAmount) * 0.4F
    // where targetAmount = horizontalDistance * 4.0F
    //
    // The 0.4F factor creates smooth acceleration/deceleration of the
    // walk cycle, preventing pop-in when entities start/stop moving.
    // Walk detection uses the smoothed value (> 0.01F) rather than
    // raw movement to avoid animation flickering at low speeds.
    //
    // See SRPLimbSwingHelper.java for a reusable utility version.
    private float prevLimbSwingAmount = 0.0F;
    private float limbSwingAmount = 0.0F;

    @Override
    public ResourceLocation getModelResource(EntityInfPig entity) {
        return MODEL;
    }

    @Override
    public ResourceLocation getTextureResource(EntityInfPig entity) {
        return TEXTURE;
    }

    @Override
    public ResourceLocation getAnimationResource(EntityInfPig entity) {
        return ANIMATION;
    }

    /**
     * Registers animation controllers with state machine logic.
     *
     * In MC 1.12.2, setRotationAngles() was called every frame with
     * embedded if/switch conditions. In GeckoLib 1.20.1, animations are
     * triggered by AnimationController based on entity state queries.
     *
     * The state machine checks conditions in priority order (highest first)
     * and plays the first matching animation. This ensures that death always
     * overrides attack, attack overrides walk, and walk overrides idle.
     *
     * Transition times are tuned to match MC 1.12.2 feel:
     *   - Attack: 3 tick snap transition (responsive combat)
     *   - Walk/Idle: 4-5 tick smooth blend (natural movement)
     *   - Evolved: 15 tick slow morph (dramatic transformation)
     *   - Sleeping: 10 tick gentle transition (peaceful rest)
     */
    @Override
    public void registerControllers(AnimatableManager.ControllerRegistrar controllers) {
        // ========================================================================
        // Main Animation Controller - State Machine
        // ========================================================================
        // Priority order: attack > walk > stage > idle
        // Each state is checked in order; the first matching condition wins.
        // Idle is always the fallback (condition: true) so the controller
        // never returns PlayState.STOP for normal entity states.
        controllers.add(new AnimationController<>(this, "mainController", 4f, event -> {
            EntityInfPig entity = event.getAnimatable();

            // ------------------------------------------------------------------
            // limbSwingAmount Lerp Update
            // ------------------------------------------------------------------
            // Update the smoothed limbSwingAmount before checking walk state.
            // This must run every tick regardless of which animation plays,
            // so the value is always up-to-date when transitioning to walk.
            float targetAmount = entity.getDeltaMovement().horizontalDistance() * 4.0F;
            this.prevLimbSwingAmount = this.limbSwingAmount;
            this.limbSwingAmount += (targetAmount - this.limbSwingAmount) * 0.4F;

            // Attack - plays once when entity has a target
            if (entity.getTarget() != null) {
                event.getController().setAnimation(
                    RawAnimation.begin().thenPlay("animation.infpig.attack")
                );
                return PlayState.CONTINUE;
            }

            // Walking - loops when entity is moving (smoothed detection)
            if (this.limbSwingAmount > 0.01F) {
                event.getController().setAnimation(
                    RawAnimation.begin().thenLoop("animation.infpig.walk")
                );
                return PlayState.CONTINUE;
            }

            // Stage - triggered by entity evolution stage
            if (entity.getStage() == 6) {
                event.getController().setAnimation(
                    RawAnimation.begin().thenLoop("animation.infpig.stage6")
                );
                return PlayState.CONTINUE;
            }

            // Idle - default fallback, always loops
            if (true) {
                event.getController().setAnimation(
                    RawAnimation.begin().thenLoop("animation.infpig.idle")
                );
                return PlayState.CONTINUE;
            }

            // No matching state - stop animation
            return PlayState.STOP;
        }));

        // ========================================================================
        // Stage Evolution Controller
        // ========================================================================
        // Different evolution stages trigger different animations.
        // This runs as a separate controller so it can override the base
        // animations when a specific stage is active.
        // In MC 1.12.2, stage checks were embedded in setRotationAngles()
        // as switch/if conditions alongside the base animation.
        controllers.add(new AnimationController<>(this, "stageController", 10f, event -> {
            EntityInfPig entity = event.getAnimatable();

            // Stage: stage6
            if (entity.getStage() == 6) {
                event.getController().setAnimation(
                    RawAnimation.begin().thenLoop("animation.infpig.stage6")
                );
                return PlayState.CONTINUE;
            }

            // No stage active - let main controller handle animation
            return PlayState.STOP;
        }));
    }
}
